version: 2.1

orbs:
  gem-tool: appfolio/gem-tool@volatile
  node: circleci/node@5.1.0

workflows:
  rc:
    jobs:
      - gem-tool/rake_test:
          name: test_ruby-<< matrix.ruby_version >>
          context: appfolio_test_context
          executor_tag: ruby
          matrix:
            parameters:
              ruby_version:
                - '3.4.1'
                - '3.3.6'
                - '3.2.5'
          after-checkout-steps:
            - node/install:
                node-version: '16.13.1'
                install-yarn: true
            - run:
                name: Run npm ci
                command: cd spec/dummy && npm ci
          after-appraisal-install-steps:
            - run:
                name: Run webpacker
                command: cd spec/dummy && bin/webpack
