version: 2.1

orbs:
  gem-tool: appfolio/gem-tool@volatile
  node: circleci/node@7.2.0
  public-packages: appfolio/public-packages@1

workflows:
  rc:
    jobs:
      - gem-tool/rake_test:
          name: test_ruby-<< matrix.ruby_version >>
          context: appfolio_test_context
          executor_tag: ruby
          matrix:
            parameters:
              ruby_version:
                - '4.0.1'
                - '3.4.8'
                - '3.3.10'
          after-checkout-steps:
            - public-packages/setup
            - run:
                name: Add dummy app bin path
                command: |
                  echo 'export PATH="$PWD/spec/dummy/bin:$PATH"' >> $BASH_ENV
            - node/install:
                node-version: '25.0.0'
            - run:
                name: Run yarn install
                command: |
                  cd spec/dummy
                  yarn install
          after-appraisal-install-steps:
            - run:
                name: Use OpenSSL legacy provider
                command: |
                  echo 'export NODE_OPTIONS="--openssl-legacy-provider"' >> $BASH_ENV
            - run:
                name: Run webpacker
                command: |
                  cd spec/dummy
                  bin/webpack
