version: 2.1

orbs:
  gem-tool: appfolio/gem-tool@volatile

workflows:
  rc:
    jobs:
      - gem-tool/rake_test:
          name: test_ruby-<< matrix.ruby_version >>
          context: appfolio_test_context
          executor_tag: ruby
          matrix:
            parameters:
              ruby_version:
                - '3.1.0-node'
                - '2.7.5-node'
                - '2.6.9-node'
          after-appraisal-install-steps:
            - run: cd spec/dummy && npm ci
